/// Word list for Atomic Notes recovery phrases.
///
/// Exactly 1024 words (2^10), so each word carries 10 bits of entropy. Sorted,
/// de-duplicated, lowercase a-z only. MUST NEVER be reordered or edited once
/// shipped: a recovery phrase is only as good as the list it was drawn from, so
/// changing an index would silently invalidate existing vaults.
///
/// Packing note: these are adjacent Dart string literals, which the compiler
/// concatenates WITHOUT inserting whitespace. Every line therefore ends with a
/// trailing space inside the quote so word boundaries survive concatenation.
/// [kWordList] splits on runs of whitespace and drops empties, so the exact
/// spacing does not matter as long as words never touch.
library;

const String _packed =
    'acorn adapt admire advance agenda airport album alley alloy alto amber '
    'amplify anchor angle ankle ant anthem anvil ape apex apple apricot '
    'apron arcade archive arena armor arrange arrow ascend aspect assemble '
    'asset atlas atom attic aurora avenue axis azure bacon badge bagel '
    'bakery balance ballad balloon ballot banana banish bank banner baritone '
    'barley barn barrel barter basil basin basket bat batch bazaar beach '
    'beacon beaker beam bean bear beard bearing beckon bee beef beige bellow '
    'bench berry bestow binary bird biscuit bison bistro blade blanket '
    'blazer blend blizzard bloom blossom boar board bolster bolt bone bonnet '
    'border bottle bough boulevard bounce bounty bowl bracelet bracket '
    'brain branch brave bread breeze brew bridge brigade brighten broaden '
    'bronze brook broom broth brush bucket buckle budget bugle bull bulletin '
    'bundle bureau burnish burst butter button cabbage cabin cabinet cable '
    'cadence cake calendar calf caliber camel camera canal candle candy '
    'canoe canopy canvas canyon cape capital capsule caption capture carbon '
    'cargo carousel carp carpet carrot carton carve cascade cashew castle '
    'cat catalog catalyst cathedral cattle cave cavern cavity cedar ceiling '
    'celery cellar cello census chain chair chalk chamber channel chapel '
    'chapter charter chassis cheese cheetah cherish cherry chick chili '
    'chill chime chisel chord chorus chrome chronicle cider cinder cinnamon '
    'cipher circuit citadel citizen clam clamp clarify clarinet clarity '
    'clause cliff climate climb clinic cloak closet cloud clove clover '
    'cluster coalition coast coat cobra cockpit cocoa coconut coffee cohort '
    'collage collar collect colt column comet commerce compact compass '
    'compose concept concert concerto concord conduit confide connect conquer '
    'consent conserve console construct context contour contract contrast '
    'convert convey convoy cookie copper coral cord corn corridor cosmos '
    'cottage couch council counter courier courtyard cover cow crab cradle '
    'craft crane crate crater cream create credit creek crescent crest '
    'crimson crisp criterion crossing crow crown crusade crystal cub cucumber '
    'cuff cultivate culture curator current curry curtain custody cyan '
    'cycle cyclone cylinder dagger date dawn debate decide declare decorate '
    'dedicate deer defend deliver delta denim density depart deploy depot '
    'descend desert detect detour develop device devise diagram dial diary '
    'digit dingo discern discover dispatch display dissolve distill dock '
    'dog dolphin domain dome donate donkey dough dove draft dragon drawer '
    'dress drift drill drizzle drought drum duck duet dune dusk dwell dynamo '
    'eagle easel ebony eclipse eel elbow elder electron element elevate '
    'elixir elk embark ember emblem embrace emerald emerge empire employ '
    'emu enact enamel enclave encore endure engage engine engrave enhance '
    'enlist enrich ensemble ensign ensure entrust envision envoy enzyme '
    'epoch equation equinox errand escort essay estate ether evolve examine '
    'exceed excel exchange exhibit exile expand expert explore express '
    'extend fable fabric factor falcon fanfare fashion fasten fathom fawn '
    'feather fedora fence ferment fern ferret ferry fiber fiddle field '
    'figure filament filter finale finch finish fish flame flea fleet flint '
    'flood flourish flower flute foal folio forest forge formal formula '
    'fort fortune fossil founder foundry fountain fox fragment freight '
    'fresco fringe frog frontier frost fusion gadget galaxy gale gallery '
    'gallop gambit garage garden garlic gather gauge gazette gear gecko '
    'genius geode geyser ginger glacier glade glide glimmer globe glove '
    'goat golden goose gopher gorilla gospel gourmet govern gown granary '
    'granite grape grasp grass gravity gravy greet grid grill grotto grove '
    'guild gusto gutter hammer handle hangar harbor hare harmony harp harvest '
    'hasten hawk heart heath heel helium helmet hen heron hinge hippo hog '
    'hoist honey honor hook hoop horizon horse hotel hound humid husky '
    'hymn ibex ignite iguana imagine improve indigo inform inquire inscribe '
    'insight inspect inspire install instruct invent invite island isotope '
    'ivory jackal jacket jade jaguar jaw jelly jersey journal jubilee juice '
    'jungle kale kayak kernel kettle kindle kite kitten knee koala ladder '
    'lagoon lake lamb lantern lark laser lasso lattice launch lavender '
    'leaf legacy legend lemon lemur lentil leopard lettuce lever lexicon '
    'liberate lighthouse lightning lilac lily lime linen lion listen lizard '
    'llama lobster locate lodge loon lotus lunar lung lynx lyric macaw '
    'magenta magnet maintain mallet manage mandolin mango manor mantle '
    'maple marble mare market maroon marsh marvel mask matter mauve meadow '
    'measure medal mediate melody melon mentor mercury merge meridian meteor '
    'metronome microbe milk mill mineral mingle mink mint mirror mist mitten '
    'mole molecule momentum monitor monsoon moon moose mosaic moss moth '
    'motivate mount mountain mouse muffin mule museum mushroom mustard '
    'myth narrate navigate navy nebula necklace nectar needle nest neutron '
    'newt nitrogen nomad noodle nourish nova nucleus nurture oar oasis '
    'oat oath obelisk observatory observe obtain ocean octave odyssey olive '
    'omen onion opal opera operate optic oracle orange orbit orchard orchid '
    'organize origin otter outline overcast overcome overture owl oxygen '
    'oyster paddle palace pallet palm pancake panda panther papaya paragon '
    'parcel pardon parka parrot particle pasta pastry patina pavilion peach '
    'peacock peak peanut pear pearl pebble pecan pelican pendant penguin '
    'pepper perceive perform persist petal photon physics piano pickle '
    'pier pigeon pillow pine pinnacle pioneer pipe pistol pixel pizza plain '
    'planet plasma plateau plaza pledge plow plum plume pocket polish pollen '
    'polymer pond ponder pony popcorn porch portal portray potato practice '
    'prairie prelude prepare present preserve pretzel prevail prism proceed '
    'produce progress prologue promote propel propose prospect protect '
    'proton provide prune pudding pulley pulse puma pump pumpkin pursue '
    'quail quantum quarry quartet quartz quasar quest quill quilt quiver '
    'rabbit raccoon racket radar radiance radio radish radius raft rainbow '
    'raisin rake rally ram rampart ranch rapture raven reactor realm reed '
    'reef refrain relic reverie rhapsody rhythm ribbon rice riddle ridge '
    'river rivet roast robe robin rock rocket rooster root rose ruby rudder '
    'ruler rune russet saddle saga sage sail salad salmon sanctum sand '
    'sandal sapphire sash satellite sauce sausage scale scarf scarlet scepter '
    'scissors scone screw scroll seal sentinel sequel serenade sesame sextant '
    'shark shawl sheep shelf shell shield shimmer shin shipyard shirt shoe '
    'shore shovel shower shrimp sickle sigil silhouette silicon silver '
    'skirt skull skunk sledge sleet sleeve slipper sloth snail snake sneaker '
    'snow sock sofa solar solo sonar sonata sonnet soprano soup spade sparrow '
    'spear spectrum sphinx spice spider spinach spindle spine spiral spool '
    'spoon sprocket squall squash squid squirrel stable stadium stag stair '
    'stamp stanza steak stencil stew stirrup stool stork storm stove studio '
    'subway sugar suit summit sunset swamp swan sweater symphony syrup '
    'tackle ';

/// The canonical word list, index 0..1023.
final List<String> kWordList =
    _packed.split(RegExp(r'\s+')).where((w) => w.isNotEmpty).toList();

/// Bits of entropy contributed by one word.
const int kBitsPerWord = 10;
